// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxOzQA7fKWH6HdrnImpeeAMC0jgizZ1GI',
    appId: '1:512603385853:web:e65e2de30fddcb8b44b394',
    messagingSenderId: '512603385853',
    projectId: 'foodisellerapp',
    authDomain: 'foodisellerapp.firebaseapp.com',
    storageBucket: 'foodisellerapp.appspot.com',
    measurementId: 'G-1RHESFBWDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRRxnzlNdI8OYCR-G1NZ1Pp-jAO-D5pO4',
    appId: '1:512603385853:android:99c6c9303b082ef744b394',
    messagingSenderId: '512603385853',
    projectId: 'foodisellerapp',
    storageBucket: 'foodisellerapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBawH_OWaQtgGoZlJXwpx6NBC3Ozt-crrQ',
    appId: '1:512603385853:ios:42d3e23a260ee70844b394',
    messagingSenderId: '512603385853',
    projectId: 'foodisellerapp',
    storageBucket: 'foodisellerapp.appspot.com',
    iosBundleId: 'com.example.foodiiRidersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBawH_OWaQtgGoZlJXwpx6NBC3Ozt-crrQ',
    appId: '1:512603385853:ios:460f2ef78922ab7a44b394',
    messagingSenderId: '512603385853',
    projectId: 'foodisellerapp',
    storageBucket: 'foodisellerapp.appspot.com',
    iosBundleId: 'com.example.foodiiRidersApp.RunnerTests',
  );
}
